name: shell_uikit
description: A simple shell ui kit.
version: 0.1.0
homepage: https://github.com/leanflutter/flutter_distributor

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  dependency_validator: ^3.0.0
