name: any_app_publisher
description: Publish your any app into popular testing or distribution platforms via Dart or the command line.
version: 0.1.0
homepage: https://fastforge.dev/any_app_publisher
repository: https://github.com/leanflutter/flutter_distributor/tree/main/packages/any_app_publisher

environment:
  sdk: ">=2.16.0 <4.0.0"

dependencies:
  flutter_app_publisher: ^0.4.5

dev_dependencies:
  dependency_validator: ^3.0.0
  mostly_reasonable_lints: ^0.1.2

executables:
  publishanyapp: main
