name: flutter_app_packager
description: Package your Flutter app into OS-specific bundles (.dmg, .exe, etc.) via Dart or the command line.
version: 0.2.6
homepage: https://github.com/leanflutter/flutter_distributor

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  app_package_maker: ^0.2.5
  archive: ^3.1.5
  args: ^2.2.0
  io: ^1.0.3
  liquid_engine: ^0.2.2
  path: ^1.8.1
  shell_executor: ^0.1.0
  yaml: ^3.1.0